name: Update Documentation

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Run tests without cache"
        default: false
        required: false
        type: boolean

jobs:
  update_docs:
    name: Deploy documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # this is necessary to get correct version of the tag
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only docs
      - name: Deploy docs
        run: |
          poetry run mkdocs gh-deploy
